config/routes.rb
Blog::Application.routes.draw do

  resources :posts do
  	resources :comments
    collection do
        get 'admin'
        get 'archive'
      end
  end

  resources :users do
    collection do
      get   'login'
      get   'register'
      post  'verify'
      get   'logout'
    end
  end
  
  resources :archives
  
  resources :categories
  
  get "welcome/index"

  root :to => 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title>Hobo Blog</title>
	<meta name="author" content="Hobo">
  <meta name="description" content="Hobo description">
  <link href="/assets/favicon.png" rel="icon">
  <%= stylesheet_link_tag "application", "screen"%>
  <%= javascript_include_tag "application","modernizr-2.0","ender", "octopress"%>
  <%= csrf_meta_tags %>
	
  <script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-28029597-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
	</script>
	
</head>
<body class="">
	<iframe style="display: none;" id="sina_anywhere_iframe"></iframe>
	<!--Header-->
  <header role="banner">
		<hgroup>
  		<h1><a href="http://www.hobo86.com">Hobo Blog</a></h1>
   	 	<h2>在路上~</h2>
		</hgroup>
	</header>
	
	<!--RSS-->
  <nav role="navigation">
  	<!--
		<ul class="subscription" data-subscription="rss">
  		<li><a href="/atom.xml" rel="subscribe-rss" title="subscribe via RSS">RSS</a></li>
		</ul>
		-->
	 	<% if @_current_user %>
    	<ul class="subscription" data-subscription="rss">
    		<li> <%= link_to @_current_user.nickname, @_current_user %></li>
  			<li> <%= link_to "Logout", logout_users_path %></li>
			</ul>
		<% else %>
    	<ul class="subscription" data-subscription="rss">
  			<li> <%= link_to "Login", login_users_path %></li>
  			<li> <%= link_to "Register", register_users_path %></li>
			</ul>
  	<% end %>
		
		<form action="http://google.com/search" method="get">
		  <fieldset role="search">
		    <input type="hidden" name="q" value="site:www.hobo86.com">
		    <input class="search" type="text" name="q" results="0" placeholder="Search">
		  </fieldset>
		</form>

		
		<ul class="main-navigation">
			<li> <%= link_to "Blog", '/' %></li>
			<li> <%= link_to "Archives", archives_path %></li>
			<li> <%= link_to "Categories", categories_path %></li>
			<li><a href="https://github.com/Hobo86" target="_blank">GitHub</a></li>
		 	<!--<li><a href="http://weibo.com/hobo86" target="_blank">微博</a></li>-->
		</ul>
	</nav>
<div id="main">
	<div id="content">
 	<% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:error] %>
    <p class="error"><%= flash[:error] %></p>
  <% end %>
	<%= yield %>
	<aside class="sidebar">
			<section class="odd">
		  	<h1>Recent Posts</h1>
		  		<ul id="recent_posts">
					<% @recent_posts.each do |post| %>
						<li class="post">
			        <%= link_to post.title, post %>
			        	</li>
					<% end %>
			 	</ul>
			</section>
			<section class="odd">
		  	<h1>Category</h1>
		  		<ul id="recent_posts">
					<% @categories_side.each do |category| %>
						<li class="post">
			        <%= link_to category.name, category %>
			      </li>
					<% end %>
			 	</ul>
			</section>
			<section class="odd">
		  	<h1>Archive</h1>
		  		<ul id="recent_posts">
					<% @archives_side.each do |archive| %>
						<li class="post">
			        <%= link_to archive.month, archive_path(archive.month) %>
			      </li>
					<% end %>
			 	</ul>
			</section>
			<section class="even">
			  <h1>About Me</h1>
			  <p>  成都云创新<br>
			      	<br>iOS
			      	<br>PHP
							<br>Ruby
			      	<br>新浪微博: <a href="http://weibo.com/hobo86" target="_blank">Steven_oO</a>
			      	<span id="wb_follow_btn">
						<span class="WB_btnA WB_widgets" node-type="followBtn">
							<span> <em class="WB_btnicn_add" node-type="followImg"></em><em>加关注</em>
							</span>
						</span>
					</span>
			  </p>
			</section>

		</aside>
		<span class="toggle-sidebar"></span>
	</div>
</div>
	
<footer role="contentinfo">
		<p>Copyright © 2013 - Hobo -
			<span class="credit">Powered by <a href="http://rubyonrails.org/" target="_blank">Ruby On Rails</a></span>
		</p>
</footer>
<script src=" http://tjs.sjs.sinajs.cn/open/api/js/wb.js?appkey=3435398785" type="text/javascript" charset="utf-8"></script>
<script>
WB2.anyWhere(function(W){
W.widget.followButton({
    uid: 1738805523,
    id: "wb_follow_btn"
    });
});
</script>

</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="background-color: #FFFEEE;">
	<h1>Hobo Blog</h1>
	<%= link_to "Home", '/' %>
	<%= link_to "Archive", archives_path %>
	<%= link_to "Category", categories_path %>
	
	<% if flash[:notice] %>
	    <p class="notice"><%= flash[:notice] %></p>
	    <% end %>
	    <% if flash[:error] %>
	    <p class="error"><%= flash[:error] %></p>
	<% end %>
	<%= yield %>

</body>
</html>